In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
vocab_size = 10000

In [6]:
one_hot_rep = [one_hot(words,vocab_size) for words in sent]
one_hot_rep

[[9130, 5581, 3517, 6426],
 [9130, 5581, 3517, 4422],
 [9130, 6851, 3517, 6161],
 [9242, 9102, 4755, 9066, 8966],
 [9242, 9102, 4755, 9066, 4727],
 [7907, 9130, 5855, 3517, 3105],
 [2123, 8765, 8256, 9066]]

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
import numpy as numpy

In [8]:
sent_len = 10
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0,    0,    0, 9130, 5581, 3517, 6426],
       [   0,    0,    0,    0,    0,    0, 9130, 5581, 3517, 4422],
       [   0,    0,    0,    0,    0,    0, 9130, 6851, 3517, 6161],
       [   0,    0,    0,    0,    0, 9242, 9102, 4755, 9066, 8966],
       [   0,    0,    0,    0,    0, 9242, 9102, 4755, 9066, 4727],
       [   0,    0,    0,    0,    0, 7907, 9130, 5855, 3517, 3105],
       [   0,    0,    0,    0,    0,    0, 2123, 8765, 8256, 9066]])

In [9]:
## feature representations

dim = 10

In [10]:
model = Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_len))
model.compile('adam','mse')

d:\projects\P_1\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[[ 8.77819210e-03, -1.97964907e-03,  2.46290453e-02,
         -4.94192131e-02,  4.26618792e-02, -6.46118075e-03,
         -3.82246599e-02, -3.02523728e-02,  4.54894416e-02,
          1.16532557e-02],
        [ 8.77819210e-03, -1.97964907e-03,  2.46290453e-02,
         -4.94192131e-02,  4.26618792e-02, -6.46118075e-03,
         -3.82246599e-02, -3.02523728e-02,  4.54894416e-02,
          1.16532557e-02],
        [ 8.77819210e-03, -1.97964907e-03,  2.46290453e-02,
         -4.94192131e-02,  4.26618792e-02, -6.46118075e-03,
         -3.82246599e-02, -3.02523728e-02,  4.54894416e-02,
          1.16532557e-02],
        [ 8.77819210e-03, -1.97964907e-03,  2.46290453e-02,
         -4.94192131e-02,  4.26618792e-02, -6.46118075e-03,
         -3.82246599e-02, -3.02523728e-02,  4.54894416e-02,
          1.16532557e-02],
        [ 8.77819210e-03, -1.97964907e-03,  2.46290453e-02,
         -4.94192131e-02,  4.26618792e-02, -6.46118075e-03,
         -3.82246599e-02, -3.02523728e-02,  4.548944

In [18]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[ 0.00877819, -0.00197965,  0.02462905, -0.04941921,  0.04266188,
        -0.00646118, -0.03822466, -0.03025237,  0.04548944,  0.01165326],
       [ 0.00877819, -0.00197965,  0.02462905, -0.04941921,  0.04266188,
        -0.00646118, -0.03822466, -0.03025237,  0.04548944,  0.01165326],
       [ 0.00877819, -0.00197965,  0.02462905, -0.04941921,  0.04266188,
        -0.00646118, -0.03822466, -0.03025237,  0.04548944,  0.01165326],
       [ 0.00877819, -0.00197965,  0.02462905, -0.04941921,  0.04266188,
        -0.00646118, -0.03822466, -0.03025237,  0.04548944,  0.01165326],
       [ 0.00877819, -0.00197965,  0.02462905, -0.04941921,  0.04266188,
        -0.00646118, -0.03822466, -0.03025237,  0.04548944,  0.01165326],
       [ 0.00877819, -0.00197965,  0.02462905, -0.04941921,  0.04266188,
        -0.00646118, -0.03822466, -0.03025237,  0.04548944,  0.01165326],
       [ 0.03909636,  0.04015242, -0.0190109 ,  0.02552382,  0.04171964,
        -0.04530695,  0.03086542, -0.04714093